### ISSUE TITLE
Does test-unit support multi thread?

### ISSUE THREAD

**Issue by ono-max** [test-unit/test-unit#204]
I'm a contributor of [ruby/debug](https://github.com/ruby/debug). We use `test-unit` for testing it(Thank you 👍 ). Currently, we consider using multi threads for faster tests. Is it possible to use `test-unit` such as assert_methods under multi threads?

Thank you.

**Comment by kou** [comment]
Could you show a sample Ruby script that show how do you want to write your assertions with multi threads?

**Comment by ono-max** [comment]
This is the example.
```ruby
def test_a
  bar
end

def bar
  [Thread.new { foo }, 
  Thread.new { foo },
  Thread.new { foo }].each(&:join)
end

def foo
  assert(false)
end
```

**Comment by kou** [comment]
Thanks.
It doesn't work because each assertion in a test must be done in the thread that runs the test.

Do you want to run multiple tests in a test for performance?
It should be done in test-unit not in a test. For example, `test_a` and `test_b` and `test_c` in the following test case should be ran in each thread with 3 threads:

```ruby
require "test-unit"

class A < Test::Unit::TestCase
  def test_a
  end

  def test_b
  end

  def test_c
  end
end
```

If this is helpful, we can implement it.

**Comment by ono-max** [comment]
> Do you want to run multiple tests in a test for performance?

Yes. However, we wouldn't like to do anything such as a test splits  into `test_a` and `test_b` and `test_c`. I'll consider an alternative way.

Thank you for giving me much detailed information!
