### ISSUE TITLE
Deprecation warnings from other gems after upgrading test-unit

### ISSUE THREAD

**Issue by ikrsni** [test-unit/test-unit#222]
After upgrading `test-unit` from `3.1.8` to `3.5.5`, I started seeing deprecation warnings from seemingly unrelated gems, for example:
```
./ruby/2.7.0/gems/faraday-0.15.4/lib/faraday.rb:68: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
```
and:
```
./bundle/ruby/2.7.0/gems/faraday-0.15.4/lib/faraday/rack_builder.rb:55: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
```

After a long investigation, I have narrowed it down to the change from `3.3.9` to `3.4.0` with the issue most likely being in:
https://github.com/test-unit/test-unit/blob/3.4.0/lib/test/unit/warning.rb#L1-L3

I am not exactly sure what is happening, but my guess would be that this piece of code ends up modifying warnings raised outside of `test-unit` scope, apparently including those in third party gems. I would appreciate if someone could take a look.

**Comment by kou** [comment]
Background: https://bugs.ruby-lang.org/issues/17591

@eregon Do we have a Ruby feature that enables deprecated warnings only for application code?

**Comment by eregon** [comment]
No, but I think it's expected deprecation warnings are global (so far at least).

@ikrsni I suppose your application depends on faraday, right?
These warnings come from executing this code, so it's not really "seemingly unrelated gems", it's dependencies.

Then I think it's valuable to see these warnings, because it means either you need to update faraday (and see if that fixes the warnings) or report the warnings to their issue tracker. If neither is done, then faraday will break on the next Ruby version, and so break your app too.

**Comment by eregon** [comment]
> suddenly cause a big increase in production logs

There was the reverse effect when deprecated warnings became no longer shown by default in Ruby 2.7.2.
Ideally it would have been done around the same time, but that's impossible since it's different pieces of the ecosystem.

I agree it can be surprising, but so it is that CRuby disabled deprecation warnings by default in 2.7.2.
I think we can close this, the warnings are valuable, just surprising in how they appear again, but ultimately one needs to deal with those warnings.

**Comment by kou** [comment]
OK. I close this.
